### ISSUE TITLE
Can't make it work using --manifest option

### ISSUE THREAD

**Issue by j2l** [RikudouSage/PwaToTwa#2]
Hi there,
I have my PWA working fine on my domain, but manifest file is only accessible directly after login, so I downloaded the manifest file locally and tried your tool with --manifest option, but it always tries to access the remote manifest file.
`./pwa-to-twa_0.0.11_18.04_bionic com.test.jotwa https://test.com/Todo_crud ./jotwa --manifest ./manifest.json
The manifest at url 'https://test.com/Todo_crud/./manifest.json' is missing these keys: short_name, theme_color, background_color, start_url`
Indeed, since it's not logged in from the CLI, manifest reroute to a login page.
The local manifest.json file is:
{
  "short_name": "PWA",
  "name": "PWA",
  "icons": [
    {
      "src": "/images/logo_512x512.png",
      "type": "image/png",
      "sizes": "512x512"
    }
  ],
  "start_url": "/index",
  "background_color": "#FFFFFF",
  "display": "standalone",
  "scope": "/",
  "theme_color": "#3F51B5"
}
About --manifest, I tried all possible combinations I think :smile: 
Any idea?

**Comment by RikudouSage** [comment]
Hello, it doesn't support local manifests as of now, I don't really see the point since it's used to convert a PWA to an application and PWA without publicly accessible manifest doesn't make much sense.

I can take a look at it when I have some free time, but it's low on my priority list.

**Comment by j2l** [comment]
Thank you

**Comment by RikudouSage** [comment]
@j2l You can now use the `--local-manifest` option.

**Comment by j2l** [comment]
Cool! Thank you very much.

**Comment by j2l** [comment]
@RikudouSage, Now it claims it can"t find `convert`. But:
```
convert --version
Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib

```
Maybe because I upgraded to 20.04?

**Comment by RikudouSage** [comment]
It doesn't say it cannot find convert, it just suggests it could be the reason. If you want further help with this problem, please send the PWA URL and the manifest file.
